name: .NET Core

on: 
  release:
    types:
      - published

jobs:
  aspnetcore:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release "./src/AspNetCore.Essentials.sln"
    - name: Run unit tests
      run: dotnet test "./src/AspNetCore.Essentials.sln"
    - name: Create the package
      run: dotnet pack --configuration Release "./src/AspNetCore.Essentials.sln"
    - name: Publish "AspNetCore.Essentials" to nuget
      run: dotnet nuget push "./src/AspNetCore.Essentials/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}